import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#f4f4f5] font-inter`}
      >
        <SidebarProvider>
          <div className="flex h-screen w-full overflow-hidden font-inter">
            <aside className="w-51.25  bg-white">{/* <SideBar /> */}</aside>

            <div className="flex flex-col  w-screen">
              <header className=" flex items-center justify-center w-full px-6 shadow-sm ">
                <Header />
              </header>
              <main className="flex-1 overflow-y-auto h-full  ">
                {children}
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
